### ISSUE TITLE
Eddystone

### ISSUE THREAD

**Issue by medrockstar** [upnext/BeaconControl#29]
Hi,

Is there any implementation of Eddystone beacon ?

Tks,

**Comment by jkurdel** [comment]
Hi @medrockstar,

Unfortunately not at this moment. The Eddystone beacon is on the product's roadmap and should be available within next few months.

**Comment by securecodeninja** [comment]
Hi @jkurdel !

Is the Eddystone support still in the roadmap? Is it already implemented?

Thanks!
