### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zkenstein** [upnext/BeaconControl#30]
I Think this is not the issue, I tried installing the app on Mac OSX, but always getting the error Could not find activesupport-4.2.0 in any of the sources lot of message present the missing gems. Is it unable to installing on Mac?

**Comment by jkurdel** [comment]
Hi @zkenstein 

We are developing BeaconControl using OS X. It is hard to help you with deployment because you didn't provide details on how you try to setup application. I suggest you to try execute bin/setup script.

**Comment by zkenstein** [comment]
Hi @jkurdel
Thanks for the reply, yes I used the bin/setup to install and I got too many errors with GEMS missing. I used El Capitant as the OS, the for Ruby I installed yang brew and also with rvm with no luck. Any clue how to solved it?

Big thanks,

**Comment by jkurdel** [comment]
Please upload your ruby version, bundler version and bundle output.

**Comment by zkenstein** [comment]
HI @jkurdel 
Finally I can installed the app correctly after reinstall several times, thank for you responded. Anyway for the database, is it possible to used XAMPP with added the mysql2 ? Tried with postresql not working, is the bin/setup also creating the DB too?

Thanks

**Comment by jkurdel** [comment]
Yes, bin/setup creates database assuming MySQL or PostgreSQL is already installed (so using MySQL from XAMPP distribution should be ok). Please look at lib/tasks/setup.rake to check which commands bin/setup script executes. 

I close this issue as it looks like your problems are not connected to BeaconControl directly but rather to basic environment setup.

Good luck with further steps to set up your own BeaconControl application.

**Comment by zkenstein** [comment]
Thanks @jkurdel for creating a nice app

**Comment by fyudelgado** [comment]
Hi Guys,

I'm trying to install BeaconControl but I have some issues with that... The error when executing ubuntu.sh shows this:

Installing ri documentation for bundler-1.15.3
Parsing documentation for bundle-0.0.1
Installing ri documentation for bundle-0.0.1
Done installing documentation for bundler, bundle after 5 seconds
2 gems installed
Succeed

[!] There was an error parsing `Gemfile`: The `branch` option for `gem 'simple_form'` is not allowed. Only gems with a git source can specify a branch. Bundler cannot continue.

 #  from /home/admuser/Proyects/BeaconControl/Gemfile:101
 #  -------------------------------------------
 #
 >  gem 'simple_form', branch: 'bootstrap-3'
 #
 #  -------------------------------------------
Failed

My versions:
Ruby 2.2.4
Bundler version 1.15.3

Any sugestions?
Regards,
Francisco Yu
