### ISSUE TITLE
[Question]Using custom map

### ISSUE THREAD

**Issue by SebastianStartup** [upnext/BeaconControl#32]
Hello everyone,
I installed the BeaconControl backend and really liked it. But after some playing around I found no easy way to configure the map. I would like to use a custom map of a shopping mall in the background to place the beacons there. Is there an easy way in the configuration files which I have overlooked?

Best
Sebastian

**Comment by jkurdel** [comment]
Hi @SebastianStartup,

We do not have any configuration option to change map. If you need to use custom map you have to write your custom code. 

Best,
Jan
