### ISSUE TITLE
Beacon Interaction with IONIC app Except SDK

### ISSUE THREAD

**Issue by Malkiat-Singh** [upnext/BeaconControl#33]
Is there any Rest API By which I can directly call API for beacon data instead to use SDK.

Because I am developing app in ionic

**Comment by jkurdel** [comment]
Hi @Malkiat-Singh,

You can only get data configured by BeaconControl app using Rest API described at https://beaconcontrol.io/dev/backend/s2s_api_docs_v1/beacons.html. We do not have any specific support for Cordova/Ionic as described here https://github.com/upnext/BeaconControl/issues/31 so if you want to get data such as beacon RSSI you have to write custom code.
