### ISSUE TITLE
Retrofit 1.9 Compatibility

### ISSUE THREAD

**Issue by Nsonni** [upnext/BeaconControl#34]
Currently this SDK does not support Retrofit 1.9 as its using 2.0.0 beta 1.

Can we create a backwards compatible branch?

**Comment by jkurdel** [comment]
Closing as a duplicate of https://github.com/upnext/BeaconControl_Android_SDK/issues/11

**Comment by Nsonni** [comment]
Could you at least refer me to where this question has been answered?

**Comment by jkurdel** [comment]
Hi @Nsonni

Sorry, I have referenced wrong issue (please see edited comment). I have closed this issue also because this is Rails project not Android SDK project.
