### ISSUE TITLE
beaconcontrol.io platform  password

### ISSUE THREAD

**Issue by GlauberF** [upnext/BeaconControl#44]
I installed the beaconcontrol.io platform, what is the default password for administrator access, where I can manage users and settings, why if I register after installed, I'm a normal user?

**Comment by mace0** [comment]
Hi,

try those:
email = ENV['SEED_ADMIN_EMAIL'] || 'admin@example.com'
password  = ENV['SEED_ADMIN_PASSWORD'] || 'test123'

**Comment by GlauberF** [comment]
Access as a normal user, as it must have a master password, to manage registered users, configure google app among other details

**Comment by mace0** [comment]
I'm afraid that I don't understand what you are talking about. I'm not sure if the system allows to manage registered users.

**Comment by GlauberF** [comment]
right,
It is returning a javascript error (google maps) as well

![erro](https://cloud.githubusercontent.com/assets/11314585/21614306/13cefecc-d1c0-11e6-88e2-6a6c681ebc79.png)

Change logo, so should everything be done through the code?

**Comment by jkurdel** [comment]
Hi @GlauberF,

Please check https://github.com/upnext/BeaconControl/issues/35 issue to resolve maps problem. I will try to update code later to make maps key configurable.

According to users management and goggle apps configuration through the admin panel I'm afraid that currently it is not supported.

Best,
Jan

**Comment by GlauberF** [comment]
ok
